// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type PasswordUpgradeQueue struct {
	UserID           pgtype.UUID
	WeakPasswordHash string
	CreatedAt        pgtype.Timestamptz
}

type Session struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	RefreshTokenHash string
	UserAgent        pgtype.Text
	IpAddress        *netip.Addr
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Email     string
	Username  string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserPassword struct {
	UserID           pgtype.UUID
	PasswordHash     pgtype.Text
	MfaSecret        pgtype.Text
	LastChangedAt    pgtype.Timestamptz
	WeakPasswordHash pgtype.Text
}
