// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserPassword(ctx context.Context, arg CreateUserPasswordParams) (CreateUserPasswordRow, error)
	CreateUserWeakPassword(ctx context.Context, arg CreateUserWeakPasswordParams) (CreateUserWeakPasswordRow, error)
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	GetSession(ctx context.Context, id pgtype.UUID) (Session, error)
	GetSessionByRefreshToken(ctx context.Context, refreshTokenHash string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserPassword(ctx context.Context, id pgtype.UUID) (GetUserPasswordRow, error)
	ListWeakPasswords(ctx context.Context, limit int32) ([]ListWeakPasswordsRow, error)
	UpgradePassword(ctx context.Context, arg UpgradePasswordParams) error
}

var _ Querier = (*Queries)(nil)
