// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token_hash, user_agent, ip_address, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, expires_at, created_at
`

type CreateSessionParams struct {
	UserID           pgtype.UUID
	RefreshTokenHash string
	UserAgent        pgtype.Text
	IpAddress        *netip.Addr
	ExpiresAt        pgtype.Timestamptz
}

type CreateSessionRow struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username)
VALUES ($1, $2)
RETURNING id, email, username, status, created_at, updated_at
`

type CreateUserParams struct {
	Email    string
	Username string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserPassword = `-- name: CreateUserPassword :one
INSERT INTO user_passwords (user_id, password_hash, weak_password_hash)
VALUES ($1, $2, $3)
RETURNING user_id, last_changed_at
`

type CreateUserPasswordParams struct {
	UserID           pgtype.UUID
	PasswordHash     pgtype.Text
	WeakPasswordHash pgtype.Text
}

type CreateUserPasswordRow struct {
	UserID        pgtype.UUID
	LastChangedAt pgtype.Timestamptz
}

func (q *Queries) CreateUserPassword(ctx context.Context, arg CreateUserPasswordParams) (CreateUserPasswordRow, error) {
	row := q.db.QueryRow(ctx, createUserPassword, arg.UserID, arg.PasswordHash, arg.WeakPasswordHash)
	var i CreateUserPasswordRow
	err := row.Scan(&i.UserID, &i.LastChangedAt)
	return i, err
}

const createUserWeakPassword = `-- name: CreateUserWeakPassword :one
INSERT INTO user_passwords (user_id, weak_password_hash)
VALUES ($1, $2)
RETURNING user_id, last_changed_at
`

type CreateUserWeakPasswordParams struct {
	UserID           pgtype.UUID
	WeakPasswordHash pgtype.Text
}

type CreateUserWeakPasswordRow struct {
	UserID        pgtype.UUID
	LastChangedAt pgtype.Timestamptz
}

func (q *Queries) CreateUserWeakPassword(ctx context.Context, arg CreateUserWeakPasswordParams) (CreateUserWeakPasswordRow, error) {
	row := q.db.QueryRow(ctx, createUserWeakPassword, arg.UserID, arg.WeakPasswordHash)
	var i CreateUserWeakPasswordRow
	err := row.Scan(&i.UserID, &i.LastChangedAt)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, expires_at, created_at FROM sessions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, refresh_token_hash, user_agent, ip_address, expires_at, created_at FROM sessions
WHERE refresh_token_hash = $1 LIMIT 1
`

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshTokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, refreshTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, status, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, email, username, status, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserById(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPassword = `-- name: GetUserPassword :one
SELECT
    u.id AS user_id,
    up.password_hash,
    up.mfa_secret,
    COALESCE(up.last_changed_at, u.updated_at, u.created_at) AS last_changed_at,
    q.weak_password_hash
FROM users u
LEFT JOIN user_passwords up ON up.user_id = u.id
LEFT JOIN password_upgrade_queue q ON q.user_id = u.id
WHERE u.id = $1 LIMIT 1
`

type GetUserPasswordRow struct {
	UserID           pgtype.UUID
	PasswordHash     pgtype.Text
	MfaSecret        pgtype.Text
	LastChangedAt    pgtype.Timestamptz
	WeakPasswordHash pgtype.Text
}

func (q *Queries) GetUserPassword(ctx context.Context, id pgtype.UUID) (GetUserPasswordRow, error) {
	row := q.db.QueryRow(ctx, getUserPassword, id)
	var i GetUserPasswordRow
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.MfaSecret,
		&i.LastChangedAt,
		&i.WeakPasswordHash,
	)
	return i, err
}

const listWeakPasswords = `-- name: ListWeakPasswords :many
SELECT
    q.user_id,
    NULL::text AS password_hash,
    NULL::text AS mfa_secret,
    q.created_at AS last_changed_at,
    q.weak_password_hash
FROM password_upgrade_queue q
ORDER BY q.created_at
LIMIT $1
`

type ListWeakPasswordsRow struct {
	UserID           pgtype.UUID
	PasswordHash     pgtype.Text
	MfaSecret        pgtype.Text
	LastChangedAt    pgtype.Timestamptz
	WeakPasswordHash string
}

func (q *Queries) ListWeakPasswords(ctx context.Context, limit int32) ([]ListWeakPasswordsRow, error) {
	rows, err := q.db.Query(ctx, listWeakPasswords, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWeakPasswordsRow
	for rows.Next() {
		var i ListWeakPasswordsRow
		if err := rows.Scan(
			&i.UserID,
			&i.PasswordHash,
			&i.MfaSecret,
			&i.LastChangedAt,
			&i.WeakPasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upgradePassword = `-- name: UpgradePassword :exec
WITH upserted AS (
    INSERT INTO user_passwords (user_id, password_hash)
    VALUES ($1, $2)
    ON CONFLICT (user_id) DO UPDATE
    SET password_hash = EXCLUDED.password_hash,
        weak_password_hash = NULL,
        last_changed_at = NOW()
    RETURNING user_id
)
DELETE FROM password_upgrade_queue
WHERE user_id IN (SELECT user_id FROM upserted)
`

type UpgradePasswordParams struct {
	UserID       pgtype.UUID
	PasswordHash pgtype.Text
}

func (q *Queries) UpgradePassword(ctx context.Context, arg UpgradePasswordParams) error {
	_, err := q.db.Exec(ctx, upgradePassword, arg.UserID, arg.PasswordHash)
	return err
}
